global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'guiapi'
    static_configs:
      - targets: ['guiapi:8080']

  - job_name: 'nutri'
    static_configs:
      - targets: ['nutri:8070']

  - job_name: 'postgres'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]

  - job_name: 'kafka'
    static_configs:
      - targets: [ 'kafka-exporter:9308' ]
